/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.0.3 (node-sequelize) on 2019-08-10 09:52:37.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

module.exports = function(sequelize, DataTypes) {
    return sequelize.define('Address', {
        address_id: {
            type: DataTypes.INTEGER,
            primaryKey: true,
            autoIncrement: true
        },
        address: {
            type: DataTypes.STRING
        },
        address2: {
            type: DataTypes.STRING
        },
        district: {
            type: DataTypes.STRING
        },
        city_id: {
            type: DataTypes.INTEGER
        },
        postal_code: {
            type: DataTypes.STRING
        },
        phone: {
            type: DataTypes.STRING
        },
        last_update: {
            type: DataTypes.DATE
        }
    }, {
        timestamps: false,
        underscored: true,
        tableName: 'address',
        syncOnAssociation: false
    });
}