/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.0.3 (node-sequelize) on 2019-08-10 09:52:37.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

module.exports = function(sequelize, DataTypes) {
    return sequelize.define('Film', {
        film_id: {
            type: DataTypes.INTEGER,
            primaryKey: true,
            autoIncrement: true
        },
        title: {
            type: DataTypes.STRING
        },
        description: {
            type: DataTypes.STRING
        },
        release_year: {
            type: DataTypes.INTEGER
        },
        language_id: {
            type: DataTypes.INTEGER
        },
        original_language_id: {
            type: DataTypes.INTEGER
        },
        rental_duration: {
            type: DataTypes.INTEGER
        },
        rental_rate: {
            type: DataTypes.DECIMAL
        },
        length: {
            type: DataTypes.INTEGER
        },
        replacement_cost: {
            type: DataTypes.DECIMAL
        },
        rating: {
            type: DataTypes.STRING
        },
        special_features: {
            type: DataTypes.STRING
        },
        last_update: {
            type: DataTypes.DATE
        }
    }, {
        timestamps: false,
        underscored: true,
        tableName: 'film',
        syncOnAssociation: false
    });
}