/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.0.3 (node-sequelize) on 2019-08-10 09:52:37.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

module.exports = function(sequelize, DataTypes) {
    return sequelize.define('FilmText', {
        film_id: {
            type: DataTypes.INTEGER,
            primaryKey: true
        },
        title: {
            type: DataTypes.STRING
        },
        description: {
            type: DataTypes.STRING
        }
    }, {
        timestamps: false,
        underscored: true,
        tableName: 'film_text',
        syncOnAssociation: false
    });
}